### ISSUE TITLE
Some question about out of memory?

### ISSUE THREAD

**Issue by upczxy** [amazon-science/earth-forecasting-transformer#20]
Hello,  In the paper you say the code can run  under a 16G GPU when batch is under 4 . but It still showed  out of the memory when I tested. What should I do

**Comment by gaozhihan** [comment]
Thanks for reporting it. You could try either
1. using smaller `micro_batch_size`, e.g. set `micro_batch_size: 2` or `micro_batch_size: 1` in `cfg.yaml` config files.
2. using [gradient checkpointing](https://pytorch.org/docs/stable/checkpoint.html) by setting `checkpoint_level: 1` or `checkpoint_level: 2` in `cfg.yaml` config files.

**Comment by upczxy** [comment]
thank you very much,the code can run now

**Comment by sxjscience** [comment]
@upczxy Let me close the issue for now. Feel free to reopen if you find any problems.
