### ISSUE TITLE
Failed to install apex

### ISSUE THREAD

**Issue by fizzking** [amazon-science/earth-forecasting-transformer#21]
I have tried to install apex as the readme requested， but have failed. What should I do？
![image](https://user-images.githubusercontent.com/111410702/200517443-e381fb0e-8853-4f5b-8d61-2cb1288463d8.png)

**Comment by gaozhihan** [comment]
Thanks for reporting it. This error seems to be related to the connections set up by your `git`. If your `git` can not work correctly, you may want to try to replace the `git clone` operation by downloading the whole repo manually. Then follow the instructions in the [official README](https://github.com/NVIDIA/apex/blob/6a40a0ad9ff3d6ebea715cf28faf39792312acbf/README.md?plain=1#L122-L129):
1. Download repo "apex" from https://github.com/NVIDIA/apex and unzip it to folder "apex".
2. Run
```
cd apex
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

**Comment by sxjscience** [comment]
@fizzking feel free to let us know if it does not work.

**Comment by fizzking** [comment]
> @fizzking feel free to let us know if it does not work.

ok i will try it as soon as possible

**Comment by fizzking** [comment]
I have tried to download apex into folder according to what you said, but still cannot install apex
![image](https://user-images.githubusercontent.com/111410702/200606356-756a5261-cb78-4cba-baa0-95440b009865.png)
![image](https://user-images.githubusercontent.com/111410702/200606370-622d6322-bf9b-4c73-829f-718f870771ad.png)

**Comment by sxjscience** [comment]
You may try the python-only installation:

`pip install -v --disable-pip-version-check --no-cache-dir ./ `

**Comment by fizzking** [comment]
Thanks！ I successfully installed apex

**Comment by sxjscience** [comment]
Great. Just let us know if you still face any issue in train the model! I will later submit a PR to revise our README to mention python-only installation of apex.

**Comment by sxjscience** [comment]
Meanwhile, let me close this first. @fizzking feel free to reopen / create new issues.
