### ISSUE TITLE
main thread is not in main loop

### ISSUE THREAD

**Issue by fizzking** [amazon-science/earth-forecasting-transformer#22]
I have tried to train earthformer on Nbody, but this error occurs, what should I do？
![image](https://user-images.githubusercontent.com/111410702/200732493-7621ee08-e386-4301-b4ae-3973993ab167.png)
![image](https://user-images.githubusercontent.com/111410702/200732503-a83ca774-eb00-4518-b188-3852ed168298.png)

,

**Comment by gaozhihan** [comment]
One possible cause is the use of `matplotlib`. Could you try to add `matplotlib.use('Agg')` where the package `matplotlib` is imported, e.g.:
```
import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot
```
You may find more related discussions in [this link](https://stackoverflow.com/questions/27147300/matplotlib-tcl-asyncdelete-async-handler-deleted-by-the-wrong-thread/29172195#29172195).

**Comment by fizzking** [comment]
是的

> One possible cause is the use of `matplotlib`. Could you try to add `matplotlib.use('Agg')` where the package `matplotlib` is imported, e.g.:
> 
> ```
> import matplotlib
> matplotlib.use('Agg')
> from matplotlib import pyplot
> ```
> 
> You may find more related discussions in [this link](https://stackoverflow.com/questions/27147300/matplotlib-tcl-asyncdelete-async-handler-deleted-by-the-wrong-thread/29172195#29172195).
Thanks a lot！I finally solved the problem according to your instructions！Since the py file is read-only, I open it as a document to modify it

**Comment by gaozhihan** [comment]
Great. Close as it has been solved. Please feel free to reopen / create new issues if you encounter any problems using the code.
