### ISSUE TITLE
Default values for CuboidTransformerModel yield assertion error

### ISSUE THREAD

**Issue by nilsleh** [amazon-science/earth-forecasting-transformer#42]
The default arguments for the CuboidTransformerModel include `enc_depth=[4, 4, 4]` and `dec_depth=[2, 2]` and during the init the line `assert len(enc_depth) == len(dec_depth)` yields an error.

**Comment by gaozhihan** [comment]
Yes. The default configs specified in the implementation of [`CuboidTransformerModel`](https://github.com/amazon-science/earth-forecasting-transformer/blob/e3a2d28f547e5cd752bd5cc35914da1034a52bf0/src/earthformer/cuboid_transformer/cuboid_transformer.py#L2797) are arbitrary. To reproduce the results shown in the paper, you may want to refer to the `cfg.yaml` file of each dataset for the exact hyperparameter configs (E.g., we set `enc_depth = [4, 4]` and `dec_depth = [4, 4]` by default for experiments on N-body MNIST using the corresponding [`cfg.yaml`](https://github.com/amazon-science/earth-forecasting-transformer/blob/e3a2d28f547e5cd752bd5cc35914da1034a52bf0/scripts/cuboid_transformer/nbody/cfg.yaml#L74-L75).).
