### ISSUE TITLE
Installation without Apex

### ISSUE THREAD

**Issue by Astralex98** [amazon-science/earth-forecasting-transformer#55]
Hello!

1. Is it possible to run your code without apex installation? Anyway I wouldn't use any distributed training so it seems that I don't need apex.

2. I have only cuda-9.0 version on my machine and your code needs lightning >= 1.6.4 which is, as far as I understand, incompatible with pytorch==1.1.0 and torchvision==0.3.0 which are stable versions for cuda-9.0. What should I do?

**Comment by gaozhihan** [comment]
#### Question 1
Sure. Taking N-body MNIST as an example, you can simply disable the usage of `Apex` by deleting the corresponding lines, i.e., [line 26](https://github.com/amazon-science/earth-forecasting-transformer/blob/0303b37178940dd27acbcb619ffd9c381731a224/scripts/cuboid_transformer/nbody/train_cuboid_nbody.py#L26) and [line 430](https://github.com/amazon-science/earth-forecasting-transformer/blob/0303b37178940dd27acbcb619ffd9c381731a224/scripts/cuboid_transformer/nbody/train_cuboid_nbody.py#L430) in [`train_cuboid_nbody.py`](https://github.com/amazon-science/earth-forecasting-transformer/blob/0303b37178940dd27acbcb619ffd9c381731a224/scripts/cuboid_transformer/nbody/train_cuboid_nbody.py#L430). Then run the training command without the settings related to multi-GPU communication:
```
python train_cuboid_nbody.py --cfg cfg.yaml --ckpt_name last.ckpt --save tmp_nbody
```
#### Question 2
We haven't tested the compatibility with lower versions of `torch`, `pytorch_lightning`, and `cuda`. My suggestion is to install `cuda-11.6` or `cuda-11.7`, ensuring compatibility with the packages specified in this repository.

**Comment by gaozhihan** [comment]
It can be problematic if your Nvidia driver version and CUDA version are mismatched. A workaround to try Earthformer without setting up CUDA is to use our [minimal test case](https://github.com/amazon-science/earth-forecasting-transformer/blob/7732b03bdb366110563516c3502315deab4c2026/tests/test_cuboid.py).

**Comment by Astralex98** [comment]
Seems that my problem is solved now. I think the issue was in overloaded server which caused the error.

Thanks again for quick supporting!
