### ISSUE TITLE
The example fails  \src\earthformer\utils\checkpoint.py

### ISSUE THREAD

**Issue by paradigm21c** [amazon-science/earth-forecasting-transformer#60]
The example fails with:
\earth-forecasting-transformer-main\src\earthformer\utils\checkpoint.py

In new pytorch lightning,
(current) from pytorch_lightning.utilities.cloud_io import load as pl_load

(Revised) from lightning_fabric.utilities.cloud_io import _load as pl_load

You may close the issue

**Comment by gaozhihan** [comment]
Thank you for bringing this issue to our attention. Please note that PyTorch Lightning does not fully support backwards compatibility between minor version updates. To avoid unexpected behavior, please verify that you are using the specific version listed in the project [README](https://github.com/amazon-science/earth-forecasting-transformer/blob/7732b03bdb366110563516c3502315deab4c2026/README.md?plain=1#L59) ([`pytorch_lightning==1.6.4`](https://lightning.ai/docs/pytorch/1.6.4/)) as we cannot guarantee compatibility with other versions.
